# Generated by Django 5.1.5 on 2025-02-20 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('transport', models.CharField(choices=[('bus', '버스'), ('subway', '지하철'), ('car', '자가용')], max_length=10)),
                ('facility', models.CharField(choices=[('convenience_store', '편의점'), ('mart', '마트'), ('laundry', '세탁소')], max_length=20)),
                ('property_type', models.CharField(choices=[('jeonse', '전세'), ('monthly', '월세'), ('sale', '매매')], max_length=10)),
                ('desired_location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=30)),
                ('image_link', models.URLField(blank=True, max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
