# Generated by Django 5.1.5 on 2025-03-20 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', '남성'), ('F', '여성')], max_length=1)),
                ('transport', models.CharField(choices=[('bus', '버스'), ('subway', '지하철'), ('car', '자가용')], max_length=10)),
                ('property_type', models.CharField(choices=[('jeonse', '전세'), ('monthly', '월세')], max_length=10)),
                ('desired_location', models.CharField(max_length=100)),
                ('preferred_facilities', models.JSONField()),
                ('jeonse_deposit_min', models.PositiveIntegerField(blank=True, null=True)),
                ('jeonse_deposit_max', models.PositiveIntegerField(blank=True, null=True)),
                ('monthly_deposit_min', models.PositiveIntegerField(blank=True, null=True)),
                ('monthly_deposit_max', models.PositiveIntegerField(blank=True, null=True)),
                ('monthly_rent_min', models.PositiveIntegerField(blank=True, null=True)),
                ('monthly_rent_max', models.PositiveIntegerField(blank=True, null=True)),
                ('recommendation_type', models.CharField(choices=[('facility', '편의시설 우선'), ('price', '시세 우선'), ('safety', '안전 우선'), ('custom', '사용자 지정')], default='facility', max_length=10)),
                ('custom_facility_weight', models.FloatField(blank=True, null=True)),
                ('custom_crime_weight', models.FloatField(blank=True, null=True)),
                ('custom_price_weight', models.FloatField(blank=True, null=True)),
                ('custom_population_weight', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_district', models.CharField(max_length=50)),
                ('cluster_dong', models.CharField(blank=True, max_length=50, null=True)),
                ('recommendation_score', models.FloatField()),
                ('cluster_lat', models.FloatField()),
                ('cluster_lng', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('input_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.recommendationinput')),
            ],
        ),
    ]
